/** Mã lỗi ổn định cho module `calls` — theo mẫu `WEARABLE_ERROR_CODES`. */
export const CALL_ERROR_CODES = {
  CALL_ALREADY_ACTIVE: 'CALL_ALREADY_ACTIVE',
  CONVERSATION_ARCHIVED: 'CONVERSATION_ARCHIVED',
  CONVERSATION_TOO_FEW_MEMBERS: 'CONVERSATION_TOO_FEW_MEMBERS',
  CALL_ALREADY_ENDED: 'CALL_ALREADY_ENDED',
  NOT_FAMILY_MEMBER: 'NOT_FAMILY_MEMBER',
  NOT_INVITED: 'NOT_INVITED',
  NOT_IN_CALL: 'NOT_IN_CALL',
  NOT_INITIATOR: 'NOT_INITIATOR',
  CALL_NOT_FOUND: 'CALL_NOT_FOUND',
  CONVERSATION_NOT_FOUND: 'CONVERSATION_NOT_FOUND',
  LIVEKIT_NOT_CONFIGURED: 'LIVEKIT_NOT_CONFIGURED',
} as const;

export const CALLS_QUEUE = 'calls';
export const CALL_TIMEOUT_JOB = 'call-timeout';

export interface CallTimeoutJobData {
  callId: string;
}
