apiVersion: v1
kind: Service
metadata:
  name: family-care-postgres
  namespace: family-care
spec:
  type: ClusterIP
  selector:
    app: family-care-postgres
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
# Backend trong Kubernetes sẽ kết nối database qua service name family-care-postgres.
