apiVersion: v1
kind: Secret
metadata:
  name: family-care-server-secret
  namespace: family-care
type: Opaque
stringData:
  DB_USERNAME: postgres
  DB_PASSWORD: postgres
  JWT_ACCESS_SECRET: change_me_access_secret_at_least_32_chars
  JWT_REFRESH_SECRET: change_me_refresh_secret_at_least_32_chars
