apiVersion: v1
kind: Service
metadata:
  name: family-care-server
  namespace: family-care
spec:
  type: NodePort
  selector:
    app: family-care-server
  ports:
    - name: http
      port: 3000
      targetPort: 3000
      nodePort: 30080

#NodePort giúp mở backend ra ngoài local Kubernetes để demo Swagger tại http://localhost:30080/api/docs.
#Trong Kubernetes, FE/Mobile/tester sẽ gọi API qua http://family-care-server:3000 (DNS nội bộ) hoặc http://localhost:30080 (NodePort).
