name: Deploy Staging to VPS

on:
  push:
    branches:
      - Staging

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            set -e

            cd /home/FAMILY_CARE_DIGITAL_MANAGEMENT
            git checkout Staging
            git pull origin Staging

            cd server
            docker compose -f docker-compose.prod.yml up -d --build

            docker ps
            curl -f http://127.0.0.1:3000/api/docs > /dev/null

            echo "Deploy staging successfully"